export const REGISTER_LAYOUT = {
  HEADER_PADDING_HORIZONTAL: 16,
  HEADER_PADDING_VERTICAL: 12,
  HEADER_TITLE_FONT_SIZE: 20,
  BACK_BUTTON_SIZE: 40,
  HEADER_BORDER_WIDTH: 1,

  TITLE_SECTION_PADDING_TOP: 40,
  TITLE_SECTION_PADDING_BOTTOM: 32,
  WELCOME_FONT_SIZE: 16,
  WELCOME_MARGIN_BOTTOM: 8,
  BRAND_NAME_FONT_SIZE: 32,
  BRAND_NAME_MARGIN_BOTTOM: 12,
  SUBTITLE_FONT_SIZE: 14,

  FORM_PADDING_HORIZONTAL: 24,

  INPUT_BORDER_RADIUS: 12,
  INPUT_PADDING_HORIZONTAL: 16,
  INPUT_PADDING_VERTICAL: 14,
  INPUT_GAP: 12,
  INPUT_BORDER_WIDTH: 1,
  INPUT_FONT_SIZE: 16,
  FLAG_FONT_SIZE: 20,
  FLAG_MARGIN_RIGHT: 8,

  BUTTON_BORDER_RADIUS: 12,
  BUTTON_PADDING_VERTICAL: 16,
  BUTTON_FONT_SIZE: 16,

  LINK_MARGIN_TOP: 24,
  LINK_FONT_SIZE: 14,
  LINK_GAP: 4,

  KEYBOARD_FOCUS_DELAY: 400,
  OTP_SENDING_DURATION: 500,
};