export const ENTRY_LAYOUT = {
  // Brand Selector
  BRAND_CARD_SIZE: 80,
  BRAND_CARD_BORDER_RADIUS: 12,
  BRAND_SCROLL_GAP: 12,
  BRAND_TEXT_SIZE: 14,
  BRAND_CARD_PADDING: 16,
  BRAND_CARD_MARGIN_BOTTOM: 5,
  BRAND_CARD_MARGIN_LEFT: 5,

  // Search Bar
  SEARCH_BAR_BORDER_RADIUS: 24,
  SEARCH_BAR_PADDING_HORIZONTAL: 16,
  SEARCH_BAR_PADDING_VERTICAL: 12,
  SEARCH_BAR_GAP: 8,
  SEARCH_BAR_FONT_SIZE: 14,

  // Quick Actions
  QUICK_ACTION_ICON_SIZE: 60,
  QUICK_ACTION_ICON_BORDER_RADIUS: 30,
  QUICK_ACTION_GAP: 8,
  QUICK_ACTION_LABEL_SIZE: 12,
  QUICK_ACTION_CONTAINER_BORDER_RADIUS: 16,
  QUICK_ACTION_CONTAINER_PADDING: 16,

  // Promo Banner
  PROMO_BANNER_MIN_HEIGHT: 120,
  PROMO_BANNER_BORDER_RADIUS: 16,
  PROMO_BANNER_PADDING: 20,
  PROMO_BANNER_GAP: 8,
  PROMO_BANNER_TITLE_SIZE: 18,
  PROMO_BANNER_SUBTITLE_SIZE: 14,
  PROMO_BANNER_SUBTITLE_LINE_HEIGHT: 20,
  PROMO_AUTO_SWIPE_INTERVAL: 3000,
  PROMO_RESUME_DELAY: 3000,

  // Pagination Dots
  PROMO_DOT_HEIGHT: 5,
  PROMO_DOT_INACTIVE_WIDTH: 25,
  PROMO_DOT_BORDER_RADIUS: 2,
  PROMO_DOT_GAP: 10,
  PROMO_DOT_BOTTOM: 10,

  // Category Scroll
  CATEGORY_ITEM_WIDTH: 80,
  CATEGORY_ICON_SIZE: 60,
  CATEGORY_ICON_BORDER_RADIUS: 30,
  CATEGORY_ICON_MARGIN_BOTTOM: 8,
  CATEGORY_SCROLL_GAP: 16,
  CATEGORY_LABEL_SIZE: 11,
  CATEGORY_SECTION_MARGIN_BOTTOM: 24,

  // Product Card
  PRODUCT_CARD_BORDER_RADIUS: 12,
  PRODUCT_CARD_MARGIN_BOTTOM: 16,
  PRODUCT_CARD_INFO_PADDING: 12,
  PRODUCT_IMAGE_ASPECT_RATIO: 1,
  PRODUCT_BADGE_TOP: 8,
  PRODUCT_BADGE_LEFT: 8,
  PRODUCT_BADGE_RIGHT: 8,
  PRODUCT_BADGE_BORDER_RADIUS: 16,
  PRODUCT_BADGE_PADDING_HORIZONTAL: 12,
  PRODUCT_BADGE_PADDING_VERTICAL: 4,
  PRODUCT_BADGE_TEXT_SIZE: 11,
  PRODUCT_DISCOUNT_BADGE_BORDER_RADIUS: 12,
  PRODUCT_DISCOUNT_BADGE_PADDING_HORIZONTAL: 8,
  PRODUCT_DISCOUNT_BADGE_PADDING_VERTICAL: 4,
  PRODUCT_NAME_SIZE: 14,
  PRODUCT_NAME_MARGIN_BOTTOM: 8,
  PRODUCT_NAME_MIN_HEIGHT: 40,
  PRODUCT_PRICE_SIZE: 16,
  PRODUCT_ORIGINAL_PRICE_SIZE: 12,
  PRODUCT_ORIGINAL_PRICE_MARGIN_TOP: 2,
  PRODUCT_ADD_BUTTON_SIZE: 32,
  PRODUCT_ADD_BUTTON_BORDER_RADIUS: 16,

  // Section
  SECTION_PADDING_HORIZONTAL: 16,
} as const;
